openapi: 3.1.0
info:
  version: 1.0.0
  title: Products app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of products app
tags:
  - name: Products
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /products:
    get:
      $ref: ../swagger/paths/products/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
