items:
  type: object
  properties:
    _id:
      type: string
      description: Product id
      example: 65e4decdd286b30065d54af9
    name:
      type: string
      description: Product name
      example: Iphone
    category:
      type: string
      description: Product category
      enum: ['books', 'electronics', 'clothing', 'other']
      example: electronics
    price:
      type: number
      description: Product price
      example: 150
    description:
      type: string
      description: Product description
      example: Iphone
